name: "Hello world workflow"
on:
  push:
    branches:
      - master
      - production
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world step"
        run: echo "Hello world"