name: "Conditional Pipeline/Workflow"
on:
  push:
    branches:
      - master
      - test

  pull_request:
    branches:
      - master
    types:
      - opened
      - closed
      
  workflow_dispatch:
     
jobs:
   on_push:
     if: github.event_name == 'push'
     runs-on: ubuntu-latest
     steps:
       - name: "Running on master push"
         run: echo "Running on master push"     
         
   on_pull_request:
      if: github.event_name == 'pull_request'
      runs-on: ubuntu-latest
      steps:
        - name: "Running on pull request"
          run: echo "Running on pull request"

   on_pull_request_opened:
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      runs-on: ubuntu-latest
      steps:
        - name: "Running on pull request opened"
          run: echo "Running on pull request has opened"

   on_pull_request_closed:
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      runs-on: ubuntu-latest
      steps:
        - name: "Running on pull request closed"
          run: echo "Running on pull request closed"

   on_workflow_dispatch:
      if: github.event_name == 'workflow_dispatch'
      runs-on: ubuntu-latest
      steps:
        - name: "Running on workflow dispatch"
          run: echo "Running on workflow dispatch"