name: "Conditional Pipeline/Workflow"
on:
  push:
    branches:
      - master
     
jobs:
   on_push:
     if: github.event_name == 'push'
     runs-on: ubuntu-latest
     steps:
       - name: "Running on master push"
         run: echo "Running on master push"     
         
   on_pull_request:
      if: github.event_name == 'pull_request'
      runs-on: ubuntu-latest
      steps:
        - name: "Running on pull request"
          run: echo "Running on pull request"